print ("'AB7'.isalpha()")
print ('AB7'.isalpha())
print ("'AB7'.isalnum()")
print ('AB7'.isalnum())
print ("'00321'.isdigit()")
print ('00321'.isdigit())
print ("cprg 216'.islower()")
print ('cprg 216'.islower())
print ("'cprg 216'.isupper()")
print ('cprg 216'.isupper())
print ("isspace test")
print (' \t\v\f\r\n'.isspace())
